import type { LucideIcon } from 'lucide-react';
import {
  AlertTriangle,
  Ban,
  BookOpen,
  Box,
  Building2,
  Cloud,
  CloudUpload,
  Code2,
  Container,
  Database,
  EyeOff,
  FileEdit,
  FolderOpen,
  GitBranch,
  Globe2,
  HardDrive,
  HelpCircle,
  Image as ImageIcon,
  Laptop,
  Layers,
  Link2,
  ListTree,
  Mail,
  MailX,
  MessageSquare,
  Monitor,
  Network,
  Scale,
  Server,
  Share2,
  Shield,
  ShieldOff,
  Table,
  Terminal,
  TimerOff,
  RefreshCw,
  TrendingUp,
  Upload,
  Usb,
  WifiOff,
} from 'lucide-react';

const rules: { test: (l: string) => boolean; Icon: LucideIcon }[] = [
  { test: l => l.includes('fastify') || l === 'koa' || l.includes('nestjs') || l.includes('nest.js'), Icon: Server },
  { test: l => l.includes('nginx') || l.includes('haproxy'), Icon: Network },
  { test: l => l.includes('terraform') || l.includes('pulumi') || l.includes('kustomize'), Icon: Layers },
  { test: l => l.includes('cloud run') || l.includes('azure static web apps') || l.includes('cloudfront'), Icon: Cloud },
  { test: l => l.includes('jquery'), Icon: Code2 },
  { test: l => l.includes('bash'), Icon: Terminal },
  { test: l => l.includes('csv'), Icon: Table },
  { test: l => l.includes('usb'), Icon: Usb },
  { test: l => l.includes('ftp'), Icon: Upload },
  { test: l => l.includes('email notification') || (l.includes('email') && !l.includes('graphql')), Icon: Mail },
  { test: l => l.includes('php mail'), Icon: MailX },
  { test: l => l.includes('local dev') || l.includes('local server') || l.includes('my computer') || l.includes('static file host'), Icon: Laptop },
  { test: l => l.includes('wordpress') || l.includes('drupal') || l.includes('/cms host') || l.includes('strapi') || l.includes('contentful'), Icon: FileEdit },
  { test: l => l.includes('redis object'), Icon: HardDrive },
  { test: l => l.includes('redis response') || l.includes('redis'), Icon: Database },
  { test: l => l.includes('mysql') || l.includes('postgres') || l.includes('mariadb') || l.includes('mongo') || l.includes('sqlite') || l.includes('database per') || l.includes('shared database') || l.includes('single shared') || l.includes('one sqlite') || l.includes('polyglot persistence') || l.includes('read replica') || l.includes('microsoft sql') || l.includes('sql server'), Icon: Database },
  {
    test: l =>
      l.includes('docker') ||
      l.includes('kubernetes') ||
      l.includes('compose') ||
      (l.includes('container') && !l.includes('no container')),
    Icon: Container,
  },
  { test: l => l.includes('vm per'), Icon: Server },
  { test: l => l.includes('consul') || l.includes('kubernetes dns') || l.includes('cloud map') || l.includes('etcd /'), Icon: Network },
  { test: l => l.includes('hardcoded ip') || l.includes('hardcoded data'), Icon: Link2 },
  { test: l => l.includes('no discovery'), Icon: WifiOff },
  { test: l => l.includes('rabbitmq') || l.includes('kafka') || l.includes('sqs') || l.includes('sns') || l.includes('async messaging') || l.includes('background job') || l.includes('saga /') || l.includes('websocket'), Icon: MessageSquare },
  { test: l => l.includes('grpc') || l.includes('rest api') || l.includes('graphql') || l.includes('trpc') || l === 'rest apis', Icon: Share2 },
  { test: l => l.includes('file system'), Icon: FolderOpen },
  { test: l => l.includes('direct http'), Icon: Link2 },
  { test: l => l.includes('react') || l.includes('vue') || l.includes('angular') || l.includes('next.js') || l.includes('nuxt') || l.includes('svelte'), Icon: Layers },
  { test: l => l.includes('hugo') || l.includes('gatsby') || l.includes('jekyll') || l.includes('eleventy') || l.includes('11ty'), Icon: BookOpen },
  { test: l => l.includes('django') || l.includes('rails') || l.includes('spring') || l.includes('laravel'), Icon: Box },
  { test: l => l.includes('express'), Icon: Server },
  { test: l => l.includes('netlify') || l.includes('vercel') || l.includes('vite +') || l.includes('github pages') || l.includes('cloudflare pages') || l.includes('fly.io') || l.includes('render (node)'), Icon: CloudUpload },
  { test: l => l.includes('heroku'), Icon: Cloud },
  { test: l => l.includes('cdn') || l.includes('edge caching') || l.includes('page cache') || l.includes('varnish') || l.includes('stale-while-revalidate') || l.includes('on-demand revalidation') || l.includes('tagged /'), Icon: Globe2 },
  { test: l => l.includes('image optimization'), Icon: ImageIcon },
  { test: l => l.includes('no optimization') || l.includes('raw file') || l.includes('raw upload'), Icon: Ban },
  { test: l => l.includes('formspree') || l.includes('serverless') || l.includes('webhook to zapier') || l.includes('separate backend api'), Icon: Cloud },
  { test: l => l.includes('git +') || l.includes('git flow') || l.includes('trunk-based') || l.includes('pr previews') || l.includes('github actions'), Icon: GitBranch },
  { test: l => l.includes('manual copy') || l.includes('no version control'), Icon: Ban },
  { test: l => l.includes('ssl') || l.includes('waf') || l.includes('2fa') || l.includes('hardening') || l.includes('rate limits') || l.includes('least-privilege'), Icon: Shield },
  { test: l => l.includes('obscurity'), Icon: EyeOff },
  { test: l => l.includes('no security'), Icon: ShieldOff },
  { test: l => l.includes('managed') || l.includes('cloud vps') || l.includes('shared hosting') || l.includes('lightsail'), Icon: Building2 },
  { test: l => l.includes('browser cache'), Icon: Monitor },
  { test: l => l.includes('no caching'), Icon: TimerOff },
  { test: l => l.includes('load balancer'), Icon: Scale },
  { test: l => l.includes('vertical scaling') || l.includes('replicas'), Icon: TrendingUp },
  { test: l => l.includes('hope') || l.includes('single server') || l.includes('single forever'), Icon: AlertTriangle },
  { test: l => l.includes('mvc') || l.includes('layered architecture') || l.includes('hexagonal') || l.includes('clean architecture') || l.includes('domain modules') || l.includes('route colocation'), Icon: ListTree },
  { test: l => l.includes('no pattern') || l.includes('random file') || l.includes('no organization') || l.includes('everything in one folder'), Icon: Ban },
  { test: l => l.includes('cloud vm') || l.includes('ansible') || l.includes('paas') || l.includes('opcache') || l.includes('nomad +') || l.includes('remix'), Icon: Server },
  { test: l => l.includes('webpack') || l.includes('aws (lambda') || l.includes('aws s3') || l.includes('rspack') || l.includes('rsbuild') || l.includes('parcel'), Icon: Cloud },
  { test: l => l.includes('zustand') || l.includes('redux') || l.includes('context +') || l.includes('mobx'), Icon: Box },
  { test: l => l.includes('localstorage'), Icon: HardDrive },
  { test: l => l.includes('feature-based') || l.includes('type-based'), Icon: ListTree },
  { test: l => l.includes('direct database') || l.includes('read json'), Icon: Ban },
  { test: l => l.includes('no build'), Icon: Ban },
  { test: l => l.includes('server-side rendering') || l.includes('incremental static'), Icon: Monitor },
  { test: l => l.includes('client-side only') || l.includes('pre-render everything'), Icon: AlertTriangle },
  { test: l => l.includes('server components') || l.includes('getserversideprops') || l.includes('getserverside'), Icon: Server },
  { test: l => l.includes('client-side fetch'), Icon: RefreshCw },
  { test: l => l.includes('event sourcing'), Icon: Layers },
  { test: l => l.includes('minify') || l.includes('tree-shake'), Icon: Box },
  { test: l => l.includes('cache headers'), Icon: TimerOff },
  { test: l => l.includes('excel'), Icon: Table },
  { test: l => l.includes('fargate') || l.includes('ecs /'), Icon: Container },
  { test: l => l.includes('htmx'), Icon: Code2 },
  { test: l => l.includes('window.*') || l.includes('window.'), Icon: Ban },
  { test: l => l.includes('create react app') || l.includes('(csr only)'), Icon: Code2 },
  { test: l => l.includes('streaming ssr') || l.includes('hybrid ssg'), Icon: Monitor },
  { test: l => l.includes('parallel loaders') || l.includes('prefetch + hydrate'), Icon: RefreshCw },
  { test: l => l.includes('don\'t support forms') || l.includes("don't support forms"), Icon: Ban },
];

export function getQuizOptionIcon(label: string): LucideIcon {
  const l = label.toLowerCase();
  for (const { test, Icon } of rules) {
    if (test(l)) return Icon;
  }
  return HelpCircle;
}

export function QuizOptionIcon({ label }: { label: string }) {
  const Icon = getQuizOptionIcon(label);
  return <Icon className="h-5 w-5 shrink-0 text-primary" strokeWidth={2} aria-hidden />;
}
